### PR TITLE
Refactoring client

### LINKED ISSUE #8: Redesign: Separate data structures from HTTP client
Currently, API is tied to `reqwest` as HTTP client so anyone who would want to use own HTTP Client would be unable to do it as `Pixiv` and `PixivRequestBuilder` are tied to it.

So what would be better if we could use
`PixivRequestBuilder` to create `PixivRequest`

And then user would need to pass `PixivRequest` to `Pixiv` for execution.

`Pixiv` itself would be in a separate module and optional, only if user would not disable default feature that enables `reqwest`

Most likely it would require to rename it.

Most likely ready to be send `PixivRequest` would its field to be public so that user could create request from it.
As most existing HTTP clients use `http` crate for basic primitives it should be easy to use it with any other clients

P.s. Well I'd like to have this separation because I prefer my own HTTP [client](https://crates.io/crates/yukikaze) to `reqwest`

### PR DESCRIPTION
**Pull request by DoumanAsh**
I started working on making `reqwest` client optional but currently stumbled of problem `reqwest` having own `Url` type instead of `http::Uri`.
This makes it somewhat difficult  and I'll need to think about it.

Meanwhile you can take a look at changed API

Closes #8

### CODE REVIEW

**Comment by fairingrey** [comment]
Looks great, thank you!

**Comment by DoumanAsh** [comment]
Oh... it was WIP actually... Please do not publish new version yet

**Comment by fairingrey** [comment]
Oh, okay. Yeah, I haven't -- I've only given a quick glimpse over it. I'll try to take a deeper look sometime later when I have time. Do you want me to revert it?

EDIT: Reverted for now, I guess we can make a new pull request for the completed PR (or talk about it further if you or I think it needs more revision)

**Comment by fairingrey** [comment]
I might have time later tonight or tomorrow, but I think I'm not against the idea of foregoing using reqwest if it makes things easier. If I recall correctly, one of the reasons I used it at the time was because it had the ability to authenticate with a bearer token, something I didn't find in the lower level HTTP clients (things have probably changed by then).

EDIT: For now, I'll go ahead and check out things directly on your fork just so I get a good idea of what's happening, and maybe make suggestions there.

**Comment by DoumanAsh** [comment]
Ok, once I'll resolve last issue I'll prepare PR again 😄

**Pull request merged**
